Get rules from #9

diff --git a/.github/workflows/blocklist.yml b/.github/workflows/blocklist.yml
--- a/.github/workflows/blocklist.yml
+++ b/.github/workflows/blocklist.yml
@@ -53,23 +53,27 @@ jobs:
           DEST_PREFIX: btn-all
         run: |
           md=$(sed -n "/^## $DEST_NAME$/,/^## /p" "$README" 2>/dev/null) || true
-          old_etag=$(echo "$md" | sed -n -E 's/^Etag: (.*)$/\1/p')
+          etag=$(echo "$md" | sed -n -E 's/^Etag: (.*)$/\1/p')
+          updated=$(echo "$md" | sed -n -E 's/^Updated: (.*)$/\1/p')
+
           new_etag=$(curl -fsSL -I "$SRC_URL" | grep -i '^etag: ' | cut -c 7- | tr -d '\r')
           if [ -z "$new_etag" ]; then
             echo "Could not fetch Etag."
-            # Continue if already generated before
-            [ -n "$old_etag" ] || exit 1
-          elif [ "$new_etag" = "$old_etag" ]; then
+            # Exit with error if fail for the first time
+            [ -n "$etag" ] || exit 1
+          elif [ "$new_etag" = "$etag" ]; then
             echo "Already up to date."
           fi
-          if [ -z "$new_etag" ] || [ "$new_etag" = "$old_etag" ]; then
-            # Keep unchanged
-            new_etag="$old_etag"
-            updated=$(echo "$md" | sed -n -E 's/^Updated: (.*)$/\1/p')
-          else
-            updated=$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M %z")
-            ./ip-to-p2p.sh --desc "$DEST_NAME" --prefix "./$DEST_PREFIX" \
-              --ip-version all --ip-version 4 "$SRC_URL" || echo "Could not generate."
+
+          if [ -n "$new_etag" ] && [ "$new_etag" != "$etag" ]; then
+            if ./ip-to-p2p.sh --desc "$DEST_NAME" --prefix "./$DEST_PREFIX" \
+              --ip-version all --ip-version 4 "$SRC_URL"; then
+              etag="$new_etag"
+              updated=$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M %z")
+            else
+              echo "Could not generate."
+              [ -n "$etag" ] || exit 1
+            fi
           fi
 
           {
@@ -77,7 +81,67 @@ jobs:
             echo ""
             echo "Source: $SRC under $SRC_LICENSE License"
             echo ""
-            echo "Etag: $new_etag"
+            echo "Etag: $etag"
+            echo ""
+            echo "Updated: $updated"
+            echo ""
+            echo "- URL: <https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$TARGET_BRANCH/$DEST_PREFIX.p2p>"
+            echo "- Cloudflare: <https://blocklist.binac.org/$DEST_PREFIX.p2p>"
+            echo "- jsDelivr: <https://cdn.jsdelivr.net/gh/$GITHUB_REPOSITORY@$TARGET_BRANCH/$DEST_PREFIX.p2p>"
+            echo "- URL (IPv4): <https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$TARGET_BRANCH/$DEST_PREFIX-ipv4.p2p>"
+            echo "- Cloudflare (IPv4): <https://blocklist.binac.org/$DEST_PREFIX-ipv4.p2p>"
+            echo "- jsDelivr (IPv4): <https://cdn.jsdelivr.net/gh/$GITHUB_REPOSITORY@$TARGET_BRANCH/$DEST_PREFIX-ipv4.p2p>"
+          } >>"$README_TMP"
+
+      - name: Generate Issue 9
+        env:
+          SRC: "[transmission-block Issue #9](https://github.com/qianbinbin/transmission-block/issues/9)"
+          SRC_URL: https://api.github.com/repos/qianbinbin/transmission-block/issues/9/comments
+          DEST_NAME: Issue9
+          DEST_PREFIX: issue9
+        run: |
+          # Etag doesn't work for GitHub API Endpoint
+          curl_gh_api() {
+            curl -fsSL \
+              -H 'Accept: application/vnd.github+json' \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H 'X-GitHub-Api-Version: 2022-11-28' "$@"
+          }
+          get_rules() {
+            url="$1"
+            while [ -n "$url" ]; do
+              headers=$(curl_gh_api -I "$1")
+              url=$(echo "$headers" | sed -n -E 's/.*<([^>]*)>; rel="next".*/\1/p')
+              content=$(curl_gh_api "$1")
+              comments=$(printf '%s\n' "$content" | jq -r '.[] | select(.author_association == "OWNER").body')
+              echo "$comments" | sed -n -E 's/^> rule: (.*$)/\1/p'
+            done
+          }
+
+          updated=$(sed -n "/^## $DEST_NAME$/,/^## /p" "$README" 2>/dev/null | sed -n -E 's/^Updated: (.*)$/\1/p')
+          if rules=$(get_rules "$SRC_URL"); then
+            RE_P2P='^[^:]*:[0-9a-fA-F\.:]+-[0-9a-fA-F\.:]+$'
+            RE_P2P_IPV4='^[^:]*:[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}-[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
+            echo "$rules" | { grep -o -E "$RE_P2P" || true; } >"./$DEST_PREFIX.p2p"
+            echo "$rules" | { grep -o -E "$RE_P2P_IPV4" || true; } >"./$DEST_PREFIX-ipv4.p2p"
+            # git diff --quiet "./$DEST_PREFIX"*  <-- doesn't work for untracked files
+            if [ -n "$(git status --porcelain "./$DEST_PREFIX"*)" ]; then
+              # echo | wc -l  <-- wrong for empty string
+              echo "Found $(wc -l "./$DEST_PREFIX.p2p" | awk '{ print $1 }') rules."
+              updated=$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M %z")
+            else
+              echo "Already up to date."
+            fi
+          else
+            echo "Could not get the rules."
+            [ -n "$updated" ] || exit 1
+          fi
+
+          {
+            echo ""
+            echo "## $DEST_NAME"
+            echo ""
+            echo "Source: $SRC"
             echo ""
             echo "Updated: $updated"
             echo ""
